pipeline {
	agent any

	environment {
		classpath="/Users/leeahreum/.p2/pool/plugins/*:classes"
	}
	
	stages {
		stage('Checkout') {
			steps {
				// 소스코드 체크아웃
				checkout scm
			}
		}

		stage('Build') {
			steps {
				// Java 파일들을 컴파일하여 생성된 클래스 파일을 classes 디렉토리에 저장
				// window  경우 bat
				sh 'echo $classpath'
				sh """
    					#!/bin/bash
	 			javac -cp $classpath -encoding UTF-8 -d classes Unit-test/src/Book.java Unit-test/src/BookManager.java Unit-test/src/BookManagerTest.java Unit-test/src/BookManagerPerformanceTest.java
     				"""
			}
		}

		stage('Test') {
			steps {
				sh """
    					java -cp $classpath org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt
	 			"""
			}
		}
	}		


	post {
		always {
			// 테스트 결과 파일을 저장하기 위해 아카이브
			archiveArtifacts 'test_results.txt'
		}
		
		
		failure {
			echo 'Build or test failed'
		}
		
		success {
			echo 'Build and test succeeded'
		}
	}
}
